language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    perl: 5.24
  - dist: bionic
    perl: 5.26
  - dist: focal
    perl: 5.32

#matrix:
# include:
#  - perl: "5.26"
#  - perl: "5.22"
#  - perl: "5.20"
#  - perl: "5.18"
#  - perl: "5.16"
#  - perl: "5.14"
#  - perl: "5.12"
#  - perl: "5.10"
#  - perl:
#sudo: false

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /doozer/
